### ISSUE TITLE
[feat-request] Save API key in variable

### ISSUE THREAD

**Issue by benthamite** [sonofhypnos/fatebook.el#1]
Thanks for creating this package.

It would be nice if the API key could be saved in a variable. I do not use `.authinfo.gpg` to store secrets; instead, I use [pass](https://github.com/NicolasPetton/pass) together with [auth-source-pass](https://www.gnu.org/software/emacs/manual/html_mono/auth.html#The-Unix-password-store). With this setup, I could store my API key with something like `(setq fatebook-api-key (auth-source-pass-get "api" "fatebook.io"))`.

**Comment by sonofhypnos** [comment]
There's `fatebook-api-key-function` for that purpose. I'll put this in the readme. Let me know if that handles your use-case.
So if you do `(setq fatebook-api-key-function (lambda () (auth-source-pass-get "api" "fatebook.io")))` that should work.

**Comment by benthamite** [comment]
Ah, that works, thanks!
